spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springchina?useUnicode=true&characterEncoding=utf-8
    username: springchina
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
