spring:
  datasource:
    url: jdbc:mysql://172.17.0.17:3306/springchina?useUnicode=true&characterEncoding=utf-8
    username: springchina
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
