spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springchina-demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    tomcat:
      initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
